development:
  adapter: postgresql
  encoding: unicode
  database: rails_react
  pool: 5
  host: localhost
  username: postgres
  password: josh5091

test:
  adapter: postgresql
  encoding: unicode
  database: rails_react
  pool: 5
  username: postgres
  password: josh5091

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
